version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.win
    volumes:
      - ./app/:/app/app
    ports:
      - 8000:8000
    env_file:
      - ./env/env.dev

  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
