version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.win
    restart: unless-stopped
    env_file:
      - ./env/env.dev
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    volumes:
      - ./app/:/app/app
      - static_volume:/app/app/staticfiles
      - media_volume:/app/app/mediafiles
    depends_on:
      - redis
      - db
    command: poetry run gunicorn --chdir /app/app api.asgi:application --bind 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker

  db:
    image: postgres:16.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  redis:
    image: redis:7.2.1
    restart: always
    ports:
      - 6379:6379

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_volume:/app/app/staticfiles
      - media_volume:/app/app/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
