# Generated by Django 4.2.5 on 2023-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["product"], name="customers_c_product_5e8d18_idx"),
        ),
    ]
