# Generated by Django 4.2.5 on 2023-10-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_cartitem_customers_c_product_5e8d18_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["is_purchased"], name="customers_c_is_purc_9539b7_idx"),
        ),
    ]
