# Generated by Django 4.2.5 on 2023-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_remove_cartitem_customers_c_product_5e8d18_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["purchased_at"], name="customers_c_purchas_2608d4_idx"),
        ),
    ]
