# Generated by Django 4.2.5 on 2023-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_cart_customers_c_purchas_2608d4_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cartitem",
            name="customers_c_product_b35338_idx",
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="customers_c_cart_id_0f23de_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["product"], name="customers_c_product_5e8d18_idx"),
        ),
    ]
