# Generated by Django 4.2.5 on 2023-10-05 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0007_rename_customers_c_purchas_a3854a_idx_cart_combined_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_combined_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_is_purchased_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_purchased_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_quantity_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_cart_product_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_product_quantity_idx",
        ),
    ]
