name: CI Workflow

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: app.api.settings.development
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
        # Reference: https://github.com/actions/setup-python/tree/main
      - uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'
      - run: make install
      - run: make lint

      - name: Run unit tests and coverage
        run: |
          make tests-units

      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v2

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "Updated coverage.svg"

      - name: Push changes
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          branch: ${{ github.ref }}