name: CI Workflow

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: app.api.settings.development
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
        # Reference: https://github.com/actions/setup-python/tree/main
      - uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'
      - run: make install
      - run: make lint
      - run: make test